import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/organisms/header/Header";
import TodoProvider from "../../contexts/TodoProvider";
import TaskProvider from "../../contexts/TaskContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <TodoProvider>
          <TaskProvider>{children}</TaskProvider>
        </TodoProvider>
      </body>
    </html>
  );
}
